version: "3.5"

services:

  rabbitmq:
    image: rabbitmq:3.8.3
    ports:
      - 15672:15672
      - 5671-5672:5671-5672
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  webhook_ingress:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8998:8000
    environment:
      - APP_NODE=${APP_NODE}
      - API_PREFIX=${API_PREFIX}
      - DEBUG=${DEBUG}
      - RABBIT_SERVER=${RABBIT_SERVER}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
